language: swift
osx_image: xcode10.2
script:
    - xcodebuild -project Cutlines.xcodeproj -scheme Cutlines -destination 'platform=iOS Simulator,OS=12.2,name=iPhone XS' -configuration Debug build test
