# A list of devices you want to take the screenshots from
devices([
"iPhone Xs"
])

languages([
  "en-US"
])

# The name of the scheme which contains the UI Tests
scheme "CutlinesUITests"

# Where should the resulting screenshots be stored?
output_directory "./screenshots"

# clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
project "./Cutlines.xcodeproj"

clear_previous_screenshots true

number_of_retries 0

# For more information about all available options run
# fastlane action snapshot
